package com.banking.cif.dao;

import com.banking.cif.model.Customer;
import com.banking.cif.util.DBConnection;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

public class CustomerDAO {

    public Customer create(Customer customer) throws SQLException {
        String sql = "INSERT INTO customers (cif_number, first_name, last_name, date_of_birth, email, kyc_status) " +
                     "VALUES (?, ?, ?, ?, ?, ?)";
        // UUID is generated by DB default, but we need it back. 
        // Or we can generate it here. The DDL says DEFAULT RANDOM_UUID().
        // Let's generate it in Java to be sure and consistent, or use RETURN_GENERATED_KEYS.
        // Using generated keys with UUIDs can be tricky in some drivers.
        // Let's generate in Java.
        
        customer.setCustomerId(UUID.randomUUID().toString());
        customer.setKycStatus("PENDING"); // Default

        sql = "INSERT INTO customers (customer_id, cif_number, first_name, last_name, date_of_birth, email, kyc_status) " +
              "VALUES (?, ?, ?, ?, ?, ?, ?)";

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            
            pstmt.setString(1, customer.getCustomerId());
            pstmt.setString(2, customer.getCifNumber());
            pstmt.setString(3, customer.getFirstName());
            pstmt.setString(4, customer.getLastName());
            pstmt.setDate(5, customer.getDateOfBirth());
            pstmt.setString(6, customer.getEmail());
            pstmt.setString(7, customer.getKycStatus());
            
            pstmt.executeUpdate();
            return customer;
        }
    }

    public Customer findById(String id) throws SQLException {
        String sql = "SELECT * FROM customers WHERE customer_id = ?";
        try (Connection conn = DBConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            
            pstmt.setString(1, id);
            try (ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    return mapResultSetToCustomer(rs);
                }
            }
        }
        return null;
    }

    public List<Customer> findByName(String name) throws SQLException {
        List<Customer> customers = new ArrayList<>();
        String sql = "SELECT * FROM customers WHERE LOWER(first_name) LIKE LOWER(?) OR LOWER(last_name) LIKE LOWER(?)";
        try (Connection conn = DBConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            
            String queryParam = "%" + name + "%";
            pstmt.setString(1, queryParam);
            pstmt.setString(2, queryParam);
            try (ResultSet rs = pstmt.executeQuery()) {
                while (rs.next()) {
                    customers.add(mapResultSetToCustomer(rs));
                }
            }
        }
        return customers;
    }
    
    public boolean emailExists(String email) throws SQLException {
        String sql = "SELECT 1 FROM customers WHERE email = ?";
        try (Connection conn = DBConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setString(1, email);
            try (ResultSet rs = pstmt.executeQuery()) {
                return rs.next();
            }
        }
    }

    private Customer mapResultSetToCustomer(ResultSet rs) throws SQLException {
        Customer c = new Customer();
        c.setCustomerId(rs.getString("customer_id"));
        c.setCifNumber(rs.getString("cif_number"));
        c.setFirstName(rs.getString("first_name"));
        c.setLastName(rs.getString("last_name"));
        c.setDateOfBirth(rs.getDate("date_of_birth"));
        c.setEmail(rs.getString("email"));
        c.setKycStatus(rs.getString("kyc_status"));
        c.setAddressLine1(rs.getString("address_line1"));
        c.setCity(rs.getString("city"));
        c.setPhoneNumber(rs.getString("phone_number"));
        c.setState(rs.getString("state"));
        c.setPostalCode(rs.getString("postal_code"));
        c.setCountryCode(rs.getString("country_code"));
        c.setRiskRating(rs.getString("risk_rating"));
        return c;
    }
}
